### ISSUE TITLE
Runbot not easily accessible

### ISSUE THREAD

**Issue by Yajo** [OCA/maintainer-tools#355] opened 2018-06-22 09:11 UTC
There's a bug currently in runbot.odoo-community.org.

When visiting the main runbot page, you get a `Upgrade-Insecure-Requests: 1` header, which makes accessing plain http runbots impossible:

![captura de pantalla de 2018-06-22 10-09-07](https://user-images.githubusercontent.com/973709/41768588-923102c6-7604-11e8-9035-5bc2287e6f20.png)

Now, when you click on the blue icon, you error, and only workaround is to copy the full URL and paste it in a new private window, without the `s` in `https://`.

**Comment by pedrobaeza** [comment] 2018-06-22 09:24
@moylop260 @gurneyalex  can you please check?

**Comment by moylop260** [comment] 2018-06-28 18:34
Is `https://` error is a deploy issue?

Or you think that is because the following fix is not applied yet to runbot:
 - https://github.com/OCA/runbot-addons/pull/157

The `?db=` parameter is not needed since that we are using just one.

**Comment by Yajo** [comment] 2018-06-29 07:49
I don't think the problem is the `?db` parameter, because it tends to work fine.

The problem seems more to be that, for that domain, https is forced, but runbots open a direct port served through plain http, which, when upgraded to https, fails.

**Comment by moylop260** [comment] 2018-06-29 23:11
Alexander,
Any clue?

**Comment by gurneyalex** [comment] 2018-07-01 18:44
@Yajo I don't understand your issue. Upgrade-Insecure-Requests is a header on the client request, not in the server answer (I don't read technical spanish but the screen capture you include has the focus on the Request headers, not the Response headers, am I correct?)

In any case I cannot reproduce your issue (I am able to access runbot builds using Firefox 60.0.2 and Chromium 66.0.3359.181

I'm closing this issue, please reopen if you can provide more information.

**Comment by Yajo** [comment] 2018-07-02 08:13
STR:

1. Go to https://runbot.odoo-community.org/runbot/repo/github-com-oca-server-auth-251
1. Click on the blue button to access one build

(Sorry I cannot reopen, please someone with permissions do it, thanks!)

**Comment by moylop260** [comment] 2018-07-04 23:33
@max3903 @gurneyalex 
Could you enable the checkbox `nginx` like `True` for all `runbot.repo`, please?

**Comment by max3903** [comment] 2018-07-05 00:04
@moylop260 Done. Only 6 repos were false:

github.com/OCA/l10n-ecuador
github.com/OCA/l10n-morocco
github.com/OCA/server-ux
github.com/OCA/server-auth
github.com/OCA/server-brand
github.com/OCA/server-backend

**Comment by moylop260** [comment] 2018-07-05 00:14
Thank you
I confirm that The issue is fixed

**Closed by moylop260** 2018-07-05 00:14 UTC
